'use client';

import { use, useEffect, useMemo, useState } from 'react';
import Link from 'next/link';
import { motion, AnimatePresence } from 'framer-motion';
import { X, ChevronRight, ChevronLeft } from 'lucide-react';
import { getRepository } from '@/lib/storage/local-repository';
import { buildWrapped, type WrappedReport } from '@/lib/insights/wrapped';
import { startOfMonth, endOfMonth, startOfYear, endOfYear } from '@/lib/utils/time';
import { monthKeyLabel } from '@/lib/utils/format';
import { Icon } from '@/components/ui/icon';
import { bandDefinition } from '@/lib/score/labels';
import { Skeleton } from '@/components/ui/skeleton';
import type { TripRecord } from '@/lib/domain/trip';
import { SPRING } from '@/components/motion/transitions';

/**
 * Road360 Wrapped — a full-screen, swipeable slide sequence.
 *
 * Slides are generated by `buildWrapped` from the same TripRecords the history
 * screen renders, so a Wrapped claim can never contradict the trip list.
 */
export default function WrappedPage({ params }: { params: Promise<{ period: string }> }) {
  const { period } = use(params);
  const isYear = period === 'year';

  const [report, setReport] = useState<WrappedReport | null>(null);
  const [index, setIndex] = useState(0);

  useEffect(() => {
    let active = true;
    void (async () => {
      const now = Date.now();
      const start = isYear ? startOfYear(now) : startOfMonth(now);
      const end = isYear ? endOfYear(now) : endOfMonth(now);

      const all: TripRecord[] = await getRepository().trips.listRecords({
        limit: 100_000,
        includeSimulated: false,
      });
      const inPeriod = all.filter((t) => t.startedAt >= start && t.startedAt <= end);

      // Same-length preceding window, for the trend slide.
      const span = end - start;
      const previous = all.filter((t) => t.startedAt >= start - span && t.startedAt < start);

      if (!active) return;
      setReport(
        buildWrapped({
          kind: isYear ? 'year' : 'month',
          label: isYear ? String(new Date(now).getFullYear()) : monthKeyLabel(new Date(now)),
          periodStart: start,
          periodEnd: end,
          trips: inPeriod,
          previousTrips: previous,
        }),
      );
    })();
    return () => {
      active = false;
    };
  }, [isYear]);

  const slide = report?.slides[index];
  const total = report?.slides.length ?? 0;

  /**
   * One colour per slide, fading to black well before the foot of the screen.
   * Wrapped is the one place the app is allowed to be saturated, but the wash
   * still has to bottom out at the same black everything else sits on or the
   * slides stop feeling like the same product.
   */
  const gradient = useMemo(() => {
    if (!slide) return 'linear-gradient(170deg, #101018 0%, #000000 60%)';
    if (slide.band) {
      const band = bandDefinition(slide.band);
      return `linear-gradient(170deg, ${band.from}38 0%, ${band.to}14 32%, #000000 68%)`;
    }
    const palettes = [
      'linear-gradient(170deg, #00E08C38 0%, #4EA8FF14 32%, #000000 68%)',
      'linear-gradient(170deg, #FFC04338 0%, #FF547014 32%, #000000 68%)',
      'linear-gradient(170deg, #6E8BFF38 0%, #00E08C14 32%, #000000 68%)',
      'linear-gradient(170deg, #FF2D5538 0%, #FF8A3D14 32%, #000000 68%)',
    ];
    return palettes[index % palettes.length]!;
  }, [slide, index]);

  if (!report) {
    return (
      <div className="min-h-dvh bg-void p-6">
        <Skeleton className="h-full min-h-[70dvh] rounded-card" />
      </div>
    );
  }

  return (
    <div className="relative min-h-dvh overflow-hidden" style={{ background: gradient }}>
      <div className="grain absolute inset-0" />

      {/* Progress bars */}
      <div className="absolute inset-x-0 top-0 z-20 flex gap-1 p-3 pt-[max(0.75rem,env(safe-area-inset-top))]">
        {report.slides.map((_, i) => (
          <div key={i} className="h-0.5 flex-1 overflow-hidden rounded-full bg-white/20">
            <div
              className="h-full bg-white transition-all duration-300"
              style={{ width: i <= index ? '100%' : '0%' }}
            />
          </div>
        ))}
      </div>

      <Link
        href="/stats"
        className="absolute top-[max(2.5rem,calc(env(safe-area-inset-top)+1.75rem))] right-4 z-20 grid size-9 place-items-center rounded-full border border-white/12 bg-black/40 text-white"
        aria-label="Close Wrapped"
      >
        <X size={18} />
      </Link>

      {/* Slide */}
      <div className="relative z-10 flex min-h-dvh flex-col items-center justify-center px-8 text-center">
        <AnimatePresence mode="wait">
          {slide ? (
            <motion.div
              key={slide.id}
              initial={{ opacity: 0, y: 30, scale: 0.96 }}
              animate={{ opacity: 1, y: 0, scale: 1 }}
              exit={{ opacity: 0, y: -30, scale: 0.96 }}
              transition={SPRING.cinematic}
              className="flex flex-col items-center gap-5"
            >
              <div className="grid size-14 place-items-center rounded-2xl border border-white/12 bg-white/8 text-white">
                <Icon name={slide.icon} size={26} />
              </div>

              <div className="text-[10px] font-semibold tracking-[0.2em] text-white/55 uppercase">
                {slide.eyebrow}
              </div>

              {slide.value ? (
                <div className="flex items-baseline justify-center gap-2">
                  <span className="num text-[76px] leading-none text-white">{slide.value}</span>
                  {slide.unit ? (
                    <span className="text-lg font-semibold text-white/60">{slide.unit}</span>
                  ) : null}
                </div>
              ) : null}

              <h1 className="text-[27px] leading-tight font-bold tracking-[-0.02em] text-white">
                {slide.headline}
              </h1>
              <p className="max-w-[19rem] text-[14px] leading-relaxed text-white/70">
                {slide.detail}
              </p>

              {slide.tripId ? (
                <Link
                  href={`/trip/${slide.tripId}`}
                  className="mt-1 inline-flex items-center gap-1 rounded-pill border border-white/15 bg-white/10 px-4 py-2 text-[13px] font-semibold text-white"
                >
                  See that drive <ChevronRight size={15} />
                </Link>
              ) : null}
            </motion.div>
          ) : null}
        </AnimatePresence>
      </div>

      {/* Tap zones for navigation */}
      <button
        type="button"
        onClick={() => setIndex((i) => Math.max(0, i - 1))}
        className="absolute inset-y-0 left-0 z-10 w-1/3"
        aria-label="Previous slide"
        disabled={index === 0}
      />
      <button
        type="button"
        onClick={() => setIndex((i) => Math.min(total - 1, i + 1))}
        className="absolute inset-y-0 right-0 z-10 w-1/3"
        aria-label="Next slide"
        disabled={index >= total - 1}
      />

      {/* Explicit controls, since invisible tap zones are not discoverable. */}
      <div className="absolute inset-x-0 bottom-0 z-20 flex items-center justify-between p-6 pb-[max(1.5rem,env(safe-area-inset-bottom))]">
        <button
          type="button"
          onClick={() => setIndex((i) => Math.max(0, i - 1))}
          disabled={index === 0}
          className="grid size-11 place-items-center rounded-full border border-white/12 bg-white/8 text-white disabled:opacity-25"
          aria-label="Previous"
        >
          <ChevronLeft size={20} />
        </button>
        <span className="num text-[12px] text-white/55">
          {index + 1} / {total}
        </span>
        <button
          type="button"
          onClick={() => setIndex((i) => Math.min(total - 1, i + 1))}
          disabled={index >= total - 1}
          className="grid size-11 place-items-center rounded-full border border-white/12 bg-white/8 text-white disabled:opacity-25"
          aria-label="Next"
        >
          <ChevronRight size={20} />
        </button>
      </div>
    </div>
  );
}
